config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :products do
      resources :prices
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product
  #accepts_nested_attributes_for :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :prices, dependent: :destroy
  #accepts_nested_attributes_for :prices, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  skip_before_action :authenticate_user!
  # def index
  #   @product = Product.find(params[:product_id])
  #   @prices = Price.all
  # end

  def show
    @price = Price.find(params[:id])
  end

  def new
    @product = Product.find(params[:product_id])
    @price = Price.new
  end

  def create
    @price = Price.new(price_params)
    @product = Product.find(params[:product_id])
    @price.product = @product
    if @price.save
      redirect_to user_products_path
    else
      render 'products/new'
    end
  end

      # def update
    #   @price = Price.find(params[:id])
      # if @price.update(product_params)
      #   redirect_to user_products_path
      # else
      #   redirect_to user_products_path
      # end
    # end

  private

  def price_params
    params.require(:price).permit(:currency, :value, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   skip_before_action :authenticate_user!
  def index
    #@user = User.find(params[:user_id])
    @products = Product.all
  end

  def new
    @user = current_user
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @user = current_user
    @product.user = current_user
    if @product.save
      redirect_to user_products_path(@products)
    else
      render :new
    end

    # def update
    #   @product = Product.find(params[:id])
      # if @product.update(product_params)
      #   redirect_to user_products_path
      # else
      #   render :edit
      # end
    # end
  end

  private

  def product_params
    params.require(:product).permit(:name, :size, :prices, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScaliaTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_price_fields.html.erb
<%= f.label :currency %>
<%= f.text_field :currency %>
<%= f.label :value %>
<%= f.number_field :value %>

app/views/products/index.html.erb
<h1>My products</h1>

<ul>
  <% @products.each do |product|  %>
    <li> <%= product.name %></li>
    <li><%= product.size %></li>
    <% product.prices.each do |price| %>
      <li><%= price.currency %></li>
      <li><%= price.value %></li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Add a product", new_user_product_path(@products) %>

app/views/products/new.html.erb
<%= form_for [@user, @product] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :size %>
  <%= f.number_field :size %>
  <%= f.submit %>
<% end %>

<%= form_for [@price] do |f| %>
<%= f.label :currency %>
<%= f.select :score, [["Eur"], ["Dollar"]]%>
<%= f.label :value %>
<%= f.number_field :value %>
<%= f.submit %>
<% end %>